schema = 3

[mod]
  [mod."github.com/Jeffail/gabs/v2"]
    version = "v2.7.0"
    hash = "sha256-Rkj6nOJ2I77baOfbXtqGVJF/WcLyn7cGqYthOZGV5Xk="
  [mod."github.com/a-h/templ"]
    version = "v0.3.819"
    hash = "sha256-uqoJL8B3IVk2snUdb3xOiiEiK6WGpIrl0VsuKpRkz8Y="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.1"
    hash = "sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ="
  [mod."github.com/delaneyj/gostar"]
    version = "v0.8.0"
    hash = "sha256-K0nm/OxEq4e3FLfUqOawMHIGkHZV69B3qJyBcLY4E9A="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.4"
    hash = "sha256-QwnR7s+bwgSM+Mf5KazzHPLYTMErkYSA2LP/ZTFOOPM="
  [mod."github.com/igrmk/treemap/v2"]
    version = "v2.0.1"
    hash = "sha256-4YFMjPiznVpQwBwBBb6SkhuNEgTHf84eZMWnGiD0RS8="
  [mod."github.com/libsql/sqlite-antlr4-parser"]
    version = "v0.0.0-20240721121621-c0bdc870f11c"
    hash = "sha256-kcH5cXCjhV9gV1Mf56RqsFdgkunaKV6qbuoNyTzRWBY="
  [mod."github.com/samber/lo"]
    version = "v1.47.0"
    hash = "sha256-jMXexVTlPdZ40STRpBLv7b+BIRqdxxra12Pl2Mj7Nz8="
  [mod."github.com/segmentio/ksuid"]
    version = "v1.0.4"
    hash = "sha256-50molk1vt8/n4Y+ruayW/EAn9NeeQ8ApmLJQVePhieE="
  [mod."github.com/tursodatabase/go-libsql"]
    version = "v0.0.0-20241221181756-6121e81fbf92"
    hash = "sha256-Kpu+PYu/k4+1JrvabDPQkt07YywM+SPEYLHZ1eCarmA="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."golang.org/x/crypto"]
    version = "v0.31.0"
    hash = "sha256-ZBjoG7ZOuTEmjaXPP9txAvjAjC46DeaLs0zrNzi8EQw="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20241217172543-b2144cdd0a67"
    hash = "sha256-b+OVYsAPa3wAJKwvxKPz3goepavGvQomsk1Rs8pnSQU="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
